spring:
  profiles:
    active: mongo-atlas
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
tweet:
  app:
    jwtSecret: dokfdsjgfdslkgjfdkkgewiukhjsdkjhf
    jwtExpirationMs: 7200000
---
Spring:
  config:
    activate:
      on-profile: mongo-atlas
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.ulnh4p7.mongodb.net/
      database: tweet-app